int draw4canvas(TH1D *passEB, TH1D *passEE, TH1D *failEB, TH1D *failEE, TCanvas *c) {
  c->Divide(2,2);
  c->cd(1);
  passEB->Draw("HIST");
  passEB->SetTitle("EB passSieie");
  c->cd(2);
  passEE->Draw("HIST");
  passEE->SetTitle("EE passSieie");
  c->cd(3);
  failEB->Draw("HIST");
  failEB->SetTitle("EB failSieie");
  c->cd(4);
  failEE->Draw("HIST");
  failEE->SetTitle("EE failSieie");

  return 0;
}

void plot_dR_cone_study() {
  gROOT->SetStyle("Plain");
  gStyle->SetPalette(1,0);
  gStyle->SetNdivisions(505);
  gStyle->SetOptStat("ourme");
  
  TFile *f = TFile::Open("../analysis/diphoton_fake_rate_closure_test_matching_QCD_Pt_all_TuneCUETP8M1_13TeV_pythia8_76X_MiniAOD_histograms.root");

  TH1D *photon_photon_pt_diff_EB_passSieie = (TH1D*) f->Get("gen_photon_reco_photon_pt_diff_EB_passSieie");
  TH1D *photon_photon_pt_diff_EE_passSieie = (TH1D*) f->Get("gen_photon_reco_photon_pt_diff_EE_passSieie");
  TH1D *photon_photon_pt_diff_EB_failSieie = (TH1D*) f->Get("gen_photon_reco_photon_pt_diff_EB_failSieie");
  TH1D *photon_photon_pt_diff_EE_failSieie = (TH1D*) f->Get("gen_photon_reco_photon_pt_diff_EE_failSieie");
  TCanvas *c_photon_photon_pt_diff = new TCanvas("c_photon_photon_pt_diff","",1500,600);
  photon_photon_pt_diff_EB_passSieie->GetXaxis()->SetTitle("gen_pt / reco_pt");
  photon_photon_pt_diff_EB_passSieie->GetXaxis()->SetRangeUser(0,2);
  photon_photon_pt_diff_EE_passSieie->GetXaxis()->SetTitle("gen_pt / reco_pt");
  photon_photon_pt_diff_EE_passSieie->GetXaxis()->SetRangeUser(0,2);
  photon_photon_pt_diff_EB_failSieie->GetXaxis()->SetTitle("gen_pt / reco_pt");
  photon_photon_pt_diff_EB_failSieie->GetXaxis()->SetRangeUser(0,2);
  photon_photon_pt_diff_EE_failSieie->GetXaxis()->SetTitle("gen_pt / reco_pt");
  photon_photon_pt_diff_EE_failSieie->GetXaxis()->SetRangeUser(0,2);
  draw4canvas(photon_photon_pt_diff_EB_passSieie,photon_photon_pt_diff_EE_passSieie,
	      photon_photon_pt_diff_EB_failSieie,photon_photon_pt_diff_EE_failSieie,
	      c_photon_photon_pt_diff);
  c_photon_photon_pt_diff->SaveAs("dR_cone_study_gen_photon_reco_photon_pt_diff.png");

  TH1D *particles_photon_pt_diff_EB_passSieie = (TH1D*) f->Get("gen_particles_reco_photon_pt_diff_EB_passSieie");
  TH1D *particles_photon_pt_diff_EE_passSieie = (TH1D*) f->Get("gen_particles_reco_photon_pt_diff_EE_passSieie");
  TH1D *particles_photon_pt_diff_EB_failSieie = (TH1D*) f->Get("gen_particles_reco_photon_pt_diff_EB_failSieie");
  TH1D *particles_photon_pt_diff_EE_failSieie = (TH1D*) f->Get("gen_particles_reco_photon_pt_diff_EE_failSieie");
  TCanvas *c_particles_photon_pt_diff = new TCanvas("c_particles_photon_pt_diff","",1500,600);
  particles_photon_pt_diff_EB_passSieie->GetXaxis()->SetTitle("sum_pt / reco_pt");
  particles_photon_pt_diff_EB_passSieie->GetXaxis()->SetRangeUser(0,2);
  particles_photon_pt_diff_EE_passSieie->GetXaxis()->SetTitle("sum_pt / reco_pt");
  particles_photon_pt_diff_EE_passSieie->GetXaxis()->SetRangeUser(0,2);
  particles_photon_pt_diff_EB_failSieie->GetXaxis()->SetTitle("sum_pt / reco_pt");
  particles_photon_pt_diff_EB_failSieie->GetXaxis()->SetRangeUser(0,2);
  particles_photon_pt_diff_EE_failSieie->GetXaxis()->SetTitle("sum_pt / reco_pt");
  particles_photon_pt_diff_EE_failSieie->GetXaxis()->SetRangeUser(0,2);
  draw4canvas(particles_photon_pt_diff_EB_passSieie,particles_photon_pt_diff_EE_passSieie,
	      particles_photon_pt_diff_EB_failSieie,particles_photon_pt_diff_EE_failSieie,
	      c_particles_photon_pt_diff);
  c_particles_photon_pt_diff->SaveAs("dR_cone_study_gen_particles_reco_photon_pt_diff.png");
  
  TH1D *siblings_photon_pt_diff_EB_passSieie = (TH1D*) f->Get("gen_siblings_reco_photon_pt_diff_EB_passSieie");
  TH1D *siblings_photon_pt_diff_EE_passSieie = (TH1D*) f->Get("gen_siblings_reco_photon_pt_diff_EE_passSieie");
  TH1D *siblings_photon_pt_diff_EB_failSieie = (TH1D*) f->Get("gen_siblings_reco_photon_pt_diff_EB_failSieie");
  TH1D *siblings_photon_pt_diff_EE_failSieie = (TH1D*) f->Get("gen_siblings_reco_photon_pt_diff_EE_failSieie");
  TCanvas *c_siblings_photon_pt_diff = new TCanvas("c_siblings_photon_pt_diff","",1500,600);
  siblings_photon_pt_diff_EB_passSieie->GetXaxis()->SetTitle("siblings_pt / reco_pt");
  siblings_photon_pt_diff_EB_passSieie->GetXaxis()->SetRangeUser(0,2);
  siblings_photon_pt_diff_EE_passSieie->GetXaxis()->SetTitle("siblings_pt / reco_pt");
  siblings_photon_pt_diff_EE_passSieie->GetXaxis()->SetRangeUser(0,2);
  siblings_photon_pt_diff_EB_failSieie->GetXaxis()->SetTitle("siblings_pt / reco_pt");
  siblings_photon_pt_diff_EB_failSieie->GetXaxis()->SetRangeUser(0,2);
  siblings_photon_pt_diff_EE_failSieie->GetXaxis()->SetTitle("siblings_pt / reco_pt");
  siblings_photon_pt_diff_EE_failSieie->GetXaxis()->SetRangeUser(0,2);
  draw4canvas(siblings_photon_pt_diff_EB_passSieie,siblings_photon_pt_diff_EE_passSieie,
	      siblings_photon_pt_diff_EB_failSieie,siblings_photon_pt_diff_EE_failSieie,
	      c_siblings_photon_pt_diff);
  c_siblings_photon_pt_diff->SaveAs("dR_cone_study_gen_siblings_reco_photon_pt_diff.png");
  
  TH1D *n_particles_EB_passSieie = (TH1D*) f->Get("n_particles_dR_cone_EB_passSieie");
  TH1D *n_particles_EE_passSieie = (TH1D*) f->Get("n_particles_dR_cone_EE_passSieie");
  TH1D *n_particles_EB_failSieie = (TH1D*) f->Get("n_particles_dR_cone_EB_failSieie");
  TH1D *n_particles_EE_failSieie = (TH1D*) f->Get("n_particles_dR_cone_EE_failSieie");
  TCanvas *c_n_particles = new TCanvas("c_n_particles","",1500,600);
  n_particles_EB_passSieie->GetXaxis()->SetTitle("Number of final state particles");
  n_particles_EE_passSieie->GetXaxis()->SetTitle("Number of final state particles");
  n_particles_EB_failSieie->GetXaxis()->SetTitle("Number of final state particles");
  n_particles_EE_failSieie->GetXaxis()->SetTitle("Number of final state particles");
  draw4canvas(n_particles_EB_passSieie,n_particles_EE_passSieie,
	      n_particles_EB_failSieie,n_particles_EE_failSieie,
	      c_n_particles);
  c_n_particles->SaveAs("dR_cone_study_n_particles.png");
  
  TH1D *n_distinct_mothers_EB_passSieie = (TH1D*) f->Get("n_distinct_mothers_dR_cone_EB_passSieie");
  TH1D *n_distinct_mothers_EE_passSieie = (TH1D*) f->Get("n_distinct_mothers_dR_cone_EE_passSieie");
  TH1D *n_distinct_mothers_EB_failSieie = (TH1D*) f->Get("n_distinct_mothers_dR_cone_EB_failSieie");
  TH1D *n_distinct_mothers_EE_failSieie = (TH1D*) f->Get("n_distinct_mothers_dR_cone_EE_failSieie");
  n_distinct_mothers_EB_passSieie->SetStats("kTrue");
  n_distinct_mothers_EB_failSieie->SetStats("kTrue");
  n_distinct_mothers_EB_passSieie->Scale(1.0/n_distinct_mothers_EB_passSieie->Integral());
  n_distinct_mothers_EE_passSieie->Scale(1.0/n_distinct_mothers_EE_passSieie->Integral());
  n_distinct_mothers_EB_failSieie->Scale(1.0/n_distinct_mothers_EB_failSieie->Integral());
  n_distinct_mothers_EE_failSieie->Scale(1.0/n_distinct_mothers_EE_failSieie->Integral());
  n_distinct_mothers_EB_failSieie->SetLineColor(kRed);
  n_distinct_mothers_EE_failSieie->SetLineColor(kRed);
  TLegend *legend_mothers_EB = new TLegend(0.60,0.65,0.80,0.85);
  legend_mothers_EB->SetBorderSize(0);
  legend_mothers_EB->SetFillColor(0);
  legend_mothers_EB->AddEntry(n_distinct_mothers_EB_passSieie,"pass sieie","l");
  legend_mothers_EB->AddEntry(n_distinct_mothers_EB_failSieie,"fail sieie","l");
  TLegend *legend_mothers_EE = new TLegend(0.60,0.65,0.80,0.85);
  legend_mothers_EE->SetBorderSize(0);
  legend_mothers_EE->SetFillColor(0);
  legend_mothers_EE->AddEntry(n_distinct_mothers_EE_passSieie,"pass sieie","l");
  legend_mothers_EE->AddEntry(n_distinct_mothers_EE_failSieie,"fail sieie","l");
  TCanvas *c_n_distinct_mothers = new TCanvas("c_n_distinct_mothers","",1500,600);
  c_n_distinct_mothers->Divide(2,1);
  c_n_distinct_mothers->cd(1);
  n_distinct_mothers_EB_passSieie->Draw("HIST");
  n_distinct_mothers_EB_failSieie->Draw("HISTsames");
  n_distinct_mothers_EB_passSieie->SetTitle("EB");
  n_distinct_mothers_EB_passSieie->GetXaxis()->SetTitle("Number of distinct mothers");
  legend_mothers_EB->Draw();
  gPad->Update();
  TPaveStats *st_EB_pass = (TPaveStats*) n_distinct_mothers_EB_passSieie->GetListOfFunctions()->FindObject("stats");
  TPaveStats *st_EB_fail = (TPaveStats*) n_distinct_mothers_EB_failSieie->GetListOfFunctions()->FindObject("stats");
  st_EB_pass->SetTextColor(kBlack);
  st_EB_pass->SetX1NDC(.45);
  st_EB_pass->SetX2NDC(.65);
  st_EB_pass->SetY1NDC(.45);
  st_EB_pass->SetY2NDC(.65);
  st_EB_fail->SetTextColor(kRed);
  st_EB_fail->SetX1NDC(.65);
  st_EB_fail->SetX2NDC(.85);
  st_EB_fail->SetY1NDC(.45);
  st_EB_fail->SetY2NDC(.65);
  gPad->Modified();
  c_n_distinct_mothers->cd(2);
  n_distinct_mothers_EE_passSieie->Draw("HIST");
  n_distinct_mothers_EE_failSieie->Draw("HISTsames");
  n_distinct_mothers_EE_passSieie->SetTitle("EE");
  n_distinct_mothers_EE_passSieie->GetXaxis()->SetTitle("Number of distinct mothers");
  legend_mothers_EE->Draw();
  gPad->Update();
  TPaveStats *st_EE_pass = (TPaveStats*) n_distinct_mothers_EE_passSieie->GetListOfFunctions()->FindObject("stats");
  TPaveStats *st_EE_fail = (TPaveStats*) n_distinct_mothers_EE_failSieie->GetListOfFunctions()->FindObject("stats");
  st_EE_pass->SetTextColor(kBlack);
  st_EE_pass->SetX1NDC(.45);
  st_EE_pass->SetX2NDC(.65);
  st_EE_pass->SetY1NDC(.45);
  st_EE_pass->SetY2NDC(.65);
  st_EE_fail->SetTextColor(kRed);
  st_EE_fail->SetX1NDC(.65);
  st_EE_fail->SetX2NDC(.85);
  st_EE_fail->SetY1NDC(.45);
  st_EE_fail->SetY2NDC(.65);
  gPad->Modified();
  c_n_distinct_mothers->SaveAs("dR_cone_study_n_distinct_mothers.png");

  // Stacked distinct mothers plot
  THStack *h_EB_passSieie = new THStack("h_EB_passSieie","");
  TH1D *n_single_pion_mothers_EB_passSieie = (TH1D*) f->Get("n_single_pion_mothers_EB_passSieie");
  TH1D *n_single_eta_mothers_EB_passSieie = (TH1D*) f->Get("n_single_eta_mothers_EB_passSieie");
  TH1D *n_single_other_mothers_EB_passSieie = (TH1D*) f->Get("n_single_other_mothers_EB_passSieie");
  n_single_pion_mothers_EB_passSieie->SetFillColor(kRed);
  n_single_eta_mothers_EB_passSieie->SetFillColor(kGreen);
  n_single_other_mothers_EB_passSieie->SetFillColor(kBlue);
  h_EB_passSieie->Add(n_single_pion_mothers_EB_passSieie);
  h_EB_passSieie->Add(n_single_eta_mothers_EB_passSieie);
  h_EB_passSieie->Add(n_single_other_mothers_EB_passSieie);
  TH1D *n_two_mothers_EB_passSieie = (TH1D*) f->Get("n_two_mothers_EB_passSieie");
  TH1D *n_three_or_more_mothers_EB_passSieie = (TH1D*) f->Get("n_three_or_more_mothers_EB_passSieie");
  THStack *h_EE_passSieie = new THStack("h_EE_passSieie","");
  TH1D *n_single_pion_mothers_EE_passSieie = (TH1D*) f->Get("n_single_pion_mothers_EE_passSieie");
  TH1D *n_single_eta_mothers_EE_passSieie = (TH1D*) f->Get("n_single_eta_mothers_EE_passSieie");
  TH1D *n_single_other_mothers_EE_passSieie = (TH1D*) f->Get("n_single_other_mothers_EE_passSieie");
  n_single_pion_mothers_EE_passSieie->SetFillColor(kRed);
  n_single_eta_mothers_EE_passSieie->SetFillColor(kGreen);
  n_single_other_mothers_EE_passSieie->SetFillColor(kBlue);
  h_EE_passSieie->Add(n_single_pion_mothers_EE_passSieie);
  h_EE_passSieie->Add(n_single_eta_mothers_EE_passSieie);
  h_EE_passSieie->Add(n_single_other_mothers_EE_passSieie);
  TH1D *n_two_mothers_EE_passSieie = (TH1D*) f->Get("n_two_mothers_EE_passSieie");
  TH1D *n_three_or_more_mothers_EE_passSieie = (TH1D*) f->Get("n_three_or_more_mothers_EE_passSieie");
  THStack *h_EB_failSieie = new THStack("h_EB_failSieie","");
  TH1D *n_single_pion_mothers_EB_failSieie = (TH1D*) f->Get("n_single_pion_mothers_EB_failSieie");
  TH1D *n_single_eta_mothers_EB_failSieie = (TH1D*) f->Get("n_single_eta_mothers_EB_failSieie");
  TH1D *n_single_other_mothers_EB_failSieie = (TH1D*) f->Get("n_single_other_mothers_EB_failSieie");
  n_single_pion_mothers_EB_failSieie->SetFillColor(kRed);
  n_single_eta_mothers_EB_failSieie->SetFillColor(kGreen);
  n_single_other_mothers_EB_failSieie->SetFillColor(kBlue);
  h_EB_failSieie->Add(n_single_pion_mothers_EB_failSieie);
  h_EB_failSieie->Add(n_single_eta_mothers_EB_failSieie);
  h_EB_failSieie->Add(n_single_other_mothers_EB_failSieie);
  TH1D *n_two_mothers_EB_failSieie = (TH1D*) f->Get("n_two_mothers_EB_failSieie");
  TH1D *n_three_or_more_mothers_EB_failSieie = (TH1D*) f->Get("n_three_or_more_mothers_EB_failSieie");
  THStack *h_EE_failSieie = new THStack("h_EE_failSieie","");
  TH1D *n_single_pion_mothers_EE_failSieie = (TH1D*) f->Get("n_single_pion_mothers_EE_failSieie");
  TH1D *n_single_eta_mothers_EE_failSieie = (TH1D*) f->Get("n_single_eta_mothers_EE_failSieie");
  TH1D *n_single_other_mothers_EE_failSieie = (TH1D*) f->Get("n_single_other_mothers_EE_failSieie");
  n_single_pion_mothers_EE_failSieie->SetFillColor(kRed);
  n_single_eta_mothers_EE_failSieie->SetFillColor(kGreen);
  n_single_other_mothers_EE_failSieie->SetFillColor(kBlue);
  h_EE_failSieie->Add(n_single_pion_mothers_EE_failSieie);
  h_EE_failSieie->Add(n_single_eta_mothers_EE_failSieie);
  h_EE_failSieie->Add(n_single_other_mothers_EE_failSieie);
  TH1D *n_two_mothers_EE_failSieie = (TH1D*) f->Get("n_two_mothers_EE_failSieie");
  TH1D *n_three_or_more_mothers_EE_failSieie = (TH1D*) f->Get("n_three_or_more_mothers_EE_failSieie");
  TLegend *legend_stacked_mothers_EB = new TLegend(0.65,0.60,0.85,0.85);
  legend_stacked_mothers_EB->SetBorderSize(0);
  legend_stacked_mothers_EB->SetFillColor(0);
  legend_stacked_mothers_EB->AddEntry(n_single_pion_mothers_EB_passSieie,"1 pi0 mother","f");
  legend_stacked_mothers_EB->AddEntry(n_single_eta_mothers_EB_passSieie,"1 eta mother","f");
  legend_stacked_mothers_EB->AddEntry(n_single_other_mothers_EB_passSieie,"1 other mother","f");
  legend_stacked_mothers_EB->AddEntry(n_two_mothers_EB_passSieie,"2 mothers","f");
  legend_stacked_mothers_EB->AddEntry(n_three_or_more_mothers_EB_passSieie,"3+ mothers","f");
  TLegend *legend_stacked_mothers_EE = new TLegend(0.65,0.60,0.85,0.85);
  legend_stacked_mothers_EE->SetBorderSize(0);
  legend_stacked_mothers_EE->SetFillColor(0);
  legend_stacked_mothers_EE->AddEntry(n_single_pion_mothers_EE_passSieie,"1 pi0 mother","f");
  legend_stacked_mothers_EE->AddEntry(n_single_eta_mothers_EE_passSieie,"1 eta mother","f");
  legend_stacked_mothers_EE->AddEntry(n_single_other_mothers_EE_passSieie,"1 other mother","f");
  legend_stacked_mothers_EE->AddEntry(n_two_mothers_EE_passSieie,"2 mothers","f");
  legend_stacked_mothers_EE->AddEntry(n_three_or_more_mothers_EE_passSieie,"3+ mothers","f");
  TCanvas *c_n_distinct_mothers_detail = new TCanvas("c_n_distinct_mothers_detail","",1500,600);
  c_n_distinct_mothers_detail->Divide(2,2);
  c_n_distinct_mothers_detail->cd(1);
  h_EB_passSieie->Draw("HIST");
  n_two_mothers_EB_passSieie->Draw("HISTsame");
  n_three_or_more_mothers_EB_passSieie->Draw("HISTsame");
  n_three_or_more_mothers_EB_passSieie->SetFillColor(kBlack);
  h_EB_passSieie->SetTitle("EB passSieie");
  h_EB_passSieie->GetXaxis()->SetTitle("Distinct mothers");
  h_EB_passSieie->GetXaxis()->SetRangeUser(0,5);
  legend_stacked_mothers_EB->Draw();
  //h_EB_passSieie->GetYaxis()->SetRangeUser(0,500);
  //h_EB_passSieie->SetStats(0);
  c_n_distinct_mothers_detail->cd(2);
  h_EE_passSieie->Draw("HIST");
  n_two_mothers_EE_passSieie->Draw("HISTsame");
  n_three_or_more_mothers_EE_passSieie->Draw("HISTsame");
  n_three_or_more_mothers_EE_passSieie->SetFillColor(kBlack);
  h_EE_passSieie->SetTitle("EE passSieie");
  h_EE_passSieie->GetXaxis()->SetTitle("Distinct mothers");
  h_EE_passSieie->GetXaxis()->SetRangeUser(0,5);
  legend_stacked_mothers_EE->Draw();
  //h_EE_passSieie->GetYaxis()->SetRangeUser(0,500);
  //h_EE_passSieie->SetStats(0);
  c_n_distinct_mothers_detail->cd(3);
  h_EB_failSieie->Draw("HIST");
  n_two_mothers_EB_failSieie->Draw("HISTsame");
  n_three_or_more_mothers_EB_failSieie->Draw("HISTsame");
  n_three_or_more_mothers_EB_failSieie->SetFillColor(kBlack);
  h_EB_failSieie->SetTitle("EB failSieie");
  h_EB_failSieie->GetXaxis()->SetTitle("Distinct mothers");
  h_EB_failSieie->GetXaxis()->SetRangeUser(0,5);
  legend_stacked_mothers_EB->Draw();
  //h_failSieie->GetYaxis()->SetRangeUser(0,500);
  //h_EB_failSieie->SetStats(0);
  c_n_distinct_mothers_detail->cd(4);
  h_EE_failSieie->Draw("HIST");
  n_two_mothers_EE_failSieie->Draw("HISTsame");
  n_three_or_more_mothers_EE_failSieie->Draw("HISTsame");
  n_three_or_more_mothers_EE_failSieie->SetFillColor(kBlack);
  h_EE_failSieie->SetTitle("EE failSieie");
  h_EE_failSieie->GetXaxis()->SetTitle("Distinct mothers");
  h_EE_failSieie->GetXaxis()->SetRangeUser(0,5);
  legend_stacked_mothers_EE->Draw();
  //g_EE_failSieie->GetYaxis()->SetRangeUser(0,500);
  //h_EE_failSieie->SetStats(0);
  c_n_distinct_mothers_detail->SaveAs("dR_cone_study_n_distinct_mothers_detail.png");

  // Stacked sieie plot
  TH1D *sieie_all_fakes_EB = (TH1D*) f->Get("sieie_all_fakes_EB");
  TH1D *sieie_one_mother_EB = (TH1D*) f->Get("sieie_one_mother_EB");
  TH1D *sieie_two_mothers_EB = (TH1D*) f->Get("sieie_two_mothers_EB");
  TH1D *sieie_three_or_more_mothers_EB = (TH1D*) f->Get("sieie_three_or_more_mothers_EB");
  sieie_all_fakes_EB->SetLineColor(kBlack);
  sieie_one_mother_EB->SetLineColor(kRed);
  sieie_two_mothers_EB->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EB->SetLineColor(kGreen+3);
  sieie_all_fakes_EB->SetMarkerColor(kBlack);
  sieie_one_mother_EB->SetMarkerColor(kRed);
  sieie_two_mothers_EB->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EB->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EB->Scale(1.0/sieie_all_fakes_EB->Integral());
  sieie_one_mother_EB->Scale(1.0/sieie_one_mother_EB->Integral());
  sieie_two_mothers_EB->Scale(1.0/sieie_two_mothers_EB->Integral());
  sieie_three_or_more_mothers_EB->Scale(1.0/sieie_three_or_more_mothers_EB->Integral());
  TH1D *sieie_all_fakes_EE = (TH1D*) f->Get("sieie_all_fakes_EE");
  TH1D *sieie_one_mother_EE = (TH1D*) f->Get("sieie_one_mother_EE");
  TH1D *sieie_two_mothers_EE = (TH1D*) f->Get("sieie_two_mothers_EE");
  TH1D *sieie_three_or_more_mothers_EE = (TH1D*) f->Get("sieie_three_or_more_mothers_EE");
  sieie_all_fakes_EE->SetLineColor(kBlack);
  sieie_one_mother_EE->SetLineColor(kRed);
  sieie_two_mothers_EE->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EE->SetLineColor(kGreen+3);
  sieie_all_fakes_EE->SetMarkerColor(kBlack);
  sieie_one_mother_EE->SetMarkerColor(kRed);
  sieie_two_mothers_EE->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EE->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EE->Scale(1.0/sieie_all_fakes_EE->Integral());
  sieie_one_mother_EE->Scale(1.0/sieie_one_mother_EE->Integral());
  sieie_two_mothers_EE->Scale(1.0/sieie_two_mothers_EE->Integral());
  sieie_three_or_more_mothers_EE->Scale(1.0/sieie_three_or_more_mothers_EE->Integral());
  TLegend *legend_EB = new TLegend(0.60,0.65,0.80,0.85);
  legend_EB->SetBorderSize(0);
  legend_EB->SetFillColor(0);
  legend_EB->AddEntry(sieie_all_fakes_EB,"all","l");
  legend_EB->AddEntry(sieie_one_mother_EB,"1 mother","l");
  legend_EB->AddEntry(sieie_two_mothers_EB,"2 mothers","l");
  legend_EB->AddEntry(sieie_three_or_more_mothers_EB,"3+ mothers","l");
  TLegend *legend_EE = new TLegend(0.60,0.65,0.80,0.85);
  legend_EE->SetBorderSize(0);
  legend_EE->SetFillColor(0);
  legend_EE->AddEntry(sieie_all_fakes_EB,"all","l");
  legend_EE->AddEntry(sieie_one_mother_EB,"1 mother","l");
  legend_EE->AddEntry(sieie_two_mothers_EB,"2 mothers","l");
  legend_EE->AddEntry(sieie_three_or_more_mothers_EB,"3+ mothers","l");
  TCanvas *c_sieie_distinct_mothers = new TCanvas("c_sieie_distinct_mothers","",1500,600);
  c_sieie_distinct_mothers->Divide(2,2);
  c_sieie_distinct_mothers->cd(1);
  sieie_all_fakes_EB->Draw("HIST");
  sieie_one_mother_EB->Draw("HISTsame");
  sieie_two_mothers_EB->Draw("HISTsame");
  sieie_three_or_more_mothers_EB->Draw("HISTsame");
  sieie_all_fakes_EB->SetTitle("EB");
  sieie_all_fakes_EB->GetXaxis()->SetRangeUser(0,0.025);
  sieie_all_fakes_EB->SetMaximum(0.2);
  sieie_all_fakes_EB->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EB->SetStats(0);
  legend_EB->Draw();
  c_sieie_distinct_mothers->cd(2);
  sieie_all_fakes_EE->Draw("HIST");
  sieie_one_mother_EE->Draw("HISTsame");
  sieie_two_mothers_EE->Draw("HISTsame");
  sieie_three_or_more_mothers_EE->Draw("HISTsame");
  sieie_all_fakes_EE->SetTitle("EE");
  sieie_all_fakes_EE->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_all_fakes_EE->SetMaximum(0.2);
  sieie_all_fakes_EE->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EE->SetStats(0);
  legend_EE->Draw();
  c_sieie_distinct_mothers->cd(3);
  sieie_all_fakes_EB->Draw("HIST");
  sieie_one_mother_EB->Draw("HISTsame");
  sieie_two_mothers_EB->Draw("HISTsame");
  sieie_three_or_more_mothers_EB->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers->cd(4);
  sieie_all_fakes_EE->Draw("HIST");
  sieie_one_mother_EE->Draw("HISTsame");
  sieie_two_mothers_EE->Draw("HISTsame");
  sieie_three_or_more_mothers_EE->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers->SaveAs("dR_cone_study_sieie_distinct_mothers.png");
  // Stacked sieie plot - pt 50To150
  TH1D *sieie_all_fakes_EB_pt_50To150 = (TH1D*) f->Get("sieie_all_fakes_EB_pt_50To150");
  TH1D *sieie_one_mother_EB_pt_50To150 = (TH1D*) f->Get("sieie_one_mother_EB_pt_50To150");
  TH1D *sieie_two_mothers_EB_pt_50To150 = (TH1D*) f->Get("sieie_two_mothers_EB_pt_50To150");
  TH1D *sieie_three_or_more_mothers_EB_pt_50To150 = (TH1D*) f->Get("sieie_three_or_more_mothers_EB_pt_50To150");
  sieie_all_fakes_EB_pt_50To150->SetLineColor(kBlack);
  sieie_one_mother_EB_pt_50To150->SetLineColor(kRed);
  sieie_two_mothers_EB_pt_50To150->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EB_pt_50To150->SetLineColor(kGreen+3);
  sieie_all_fakes_EB_pt_50To150->SetMarkerColor(kBlack);
  sieie_one_mother_EB_pt_50To150->SetMarkerColor(kRed);
  sieie_two_mothers_EB_pt_50To150->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EB_pt_50To150->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EB_pt_50To150->Scale(1.0/sieie_all_fakes_EB_pt_50To150->Integral());
  sieie_one_mother_EB_pt_50To150->Scale(1.0/sieie_one_mother_EB_pt_50To150->Integral());
  sieie_two_mothers_EB_pt_50To150->Scale(1.0/sieie_two_mothers_EB_pt_50To150->Integral());
  sieie_three_or_more_mothers_EB_pt_50To150->Scale(1.0/sieie_three_or_more_mothers_EB_pt_50To150->Integral());
  TH1D *sieie_all_fakes_EE_pt_50To150 = (TH1D*) f->Get("sieie_all_fakes_EE_pt_50To150");
  TH1D *sieie_one_mother_EE_pt_50To150 = (TH1D*) f->Get("sieie_one_mother_EE_pt_50To150");
  TH1D *sieie_two_mothers_EE_pt_50To150 = (TH1D*) f->Get("sieie_two_mothers_EE_pt_50To150");
  TH1D *sieie_three_or_more_mothers_EE_pt_50To150 = (TH1D*) f->Get("sieie_three_or_more_mothers_EE_pt_50To150");
  sieie_all_fakes_EE_pt_50To150->SetLineColor(kBlack);
  sieie_one_mother_EE_pt_50To150->SetLineColor(kRed);
  sieie_two_mothers_EE_pt_50To150->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EE_pt_50To150->SetLineColor(kGreen+3);
  sieie_all_fakes_EE_pt_50To150->SetMarkerColor(kBlack);
  sieie_one_mother_EE_pt_50To150->SetMarkerColor(kRed);
  sieie_two_mothers_EE_pt_50To150->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EE_pt_50To150->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EE_pt_50To150->Scale(1.0/sieie_all_fakes_EE_pt_50To150->Integral());
  sieie_one_mother_EE_pt_50To150->Scale(1.0/sieie_one_mother_EE_pt_50To150->Integral());
  sieie_two_mothers_EE_pt_50To150->Scale(1.0/sieie_two_mothers_EE_pt_50To150->Integral());
  sieie_three_or_more_mothers_EE_pt_50To150->Scale(1.0/sieie_three_or_more_mothers_EE_pt_50To150->Integral());
  TLegend *legend_EB_pt_50To150 = new TLegend(0.60,0.65,0.80,0.85);
  legend_EB_pt_50To150->SetBorderSize(0);
  legend_EB_pt_50To150->SetFillColor(0);
  legend_EB_pt_50To150->AddEntry(sieie_all_fakes_EB_pt_50To150,"all","l");
  legend_EB_pt_50To150->AddEntry(sieie_one_mother_EB_pt_50To150,"1 mother","l");
  legend_EB_pt_50To150->AddEntry(sieie_two_mothers_EB_pt_50To150,"2 mothers","l");
  legend_EB_pt_50To150->AddEntry(sieie_three_or_more_mothers_EB_pt_50To150,"3+ mothers","l");
  TLegend *legend_EE_pt_50To150 = new TLegend(0.60,0.65,0.80,0.85);
  legend_EE_pt_50To150->SetBorderSize(0);
  legend_EE_pt_50To150->SetFillColor(0);
  legend_EE_pt_50To150->AddEntry(sieie_all_fakes_EB_pt_50To150,"all","l");
  legend_EE_pt_50To150->AddEntry(sieie_one_mother_EB_pt_50To150,"1 mother","l");
  legend_EE_pt_50To150->AddEntry(sieie_two_mothers_EB_pt_50To150,"2 mothers","l");
  legend_EE_pt_50To150->AddEntry(sieie_three_or_more_mothers_EB_pt_50To150,"3+ mothers","l");
  TCanvas *c_sieie_distinct_mothers_pt_50To150 = new TCanvas("c_sieie_distinct_mothers_pt_50To150","",1500,600);
  c_sieie_distinct_mothers_pt_50To150->Divide(2,2);
  c_sieie_distinct_mothers_pt_50To150->cd(1);
  sieie_all_fakes_EB_pt_50To150->Draw("HIST");
  sieie_one_mother_EB_pt_50To150->Draw("HISTsame");
  sieie_two_mothers_EB_pt_50To150->Draw("HISTsame");
  sieie_three_or_more_mothers_EB_pt_50To150->Draw("HISTsame");
  sieie_all_fakes_EB_pt_50To150->SetTitle("EB_pt_50To150");
  sieie_all_fakes_EB_pt_50To150->GetXaxis()->SetRangeUser(0,0.025);
  sieie_all_fakes_EB_pt_50To150->SetMaximum(0.2);
  sieie_all_fakes_EB_pt_50To150->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EB_pt_50To150->SetStats(0);
  legend_EB_pt_50To150->Draw();
  c_sieie_distinct_mothers_pt_50To150->cd(2);
  sieie_all_fakes_EE_pt_50To150->Draw("HIST");
  sieie_one_mother_EE_pt_50To150->Draw("HISTsame");
  sieie_two_mothers_EE_pt_50To150->Draw("HISTsame");
  sieie_three_or_more_mothers_EE_pt_50To150->Draw("HISTsame");
  sieie_all_fakes_EE_pt_50To150->SetTitle("EE_pt_50To150");
  sieie_all_fakes_EE_pt_50To150->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_all_fakes_EE_pt_50To150->SetMaximum(0.2);
  sieie_all_fakes_EE_pt_50To150->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EE_pt_50To150->SetStats(0);
  legend_EE_pt_50To150->Draw();
  c_sieie_distinct_mothers_pt_50To150->cd(3);
  sieie_all_fakes_EB_pt_50To150->Draw("HIST");
  sieie_one_mother_EB_pt_50To150->Draw("HISTsame");
  sieie_two_mothers_EB_pt_50To150->Draw("HISTsame");
  sieie_three_or_more_mothers_EB_pt_50To150->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers_pt_50To150->cd(4);
  sieie_all_fakes_EE_pt_50To150->Draw("HIST");
  sieie_one_mother_EE_pt_50To150->Draw("HISTsame");
  sieie_two_mothers_EE_pt_50To150->Draw("HISTsame");
  sieie_three_or_more_mothers_EE_pt_50To150->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers_pt_50To150->SaveAs("dR_cone_study_sieie_distinct_mothers_pt_50To150.png");
  // Stacked sieie plot - pt 150To300
  TH1D *sieie_all_fakes_EB_pt_150To300 = (TH1D*) f->Get("sieie_all_fakes_EB_pt_150To300");
  TH1D *sieie_one_mother_EB_pt_150To300 = (TH1D*) f->Get("sieie_one_mother_EB_pt_150To300");
  TH1D *sieie_two_mothers_EB_pt_150To300 = (TH1D*) f->Get("sieie_two_mothers_EB_pt_150To300");
  TH1D *sieie_three_or_more_mothers_EB_pt_150To300 = (TH1D*) f->Get("sieie_three_or_more_mothers_EB_pt_150To300");
  sieie_all_fakes_EB_pt_150To300->SetLineColor(kBlack);
  sieie_one_mother_EB_pt_150To300->SetLineColor(kRed);
  sieie_two_mothers_EB_pt_150To300->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EB_pt_150To300->SetLineColor(kGreen+3);
  sieie_all_fakes_EB_pt_150To300->SetMarkerColor(kBlack);
  sieie_one_mother_EB_pt_150To300->SetMarkerColor(kRed);
  sieie_two_mothers_EB_pt_150To300->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EB_pt_150To300->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EB_pt_150To300->Scale(1.0/sieie_all_fakes_EB_pt_150To300->Integral());
  sieie_one_mother_EB_pt_150To300->Scale(1.0/sieie_one_mother_EB_pt_150To300->Integral());
  sieie_two_mothers_EB_pt_150To300->Scale(1.0/sieie_two_mothers_EB_pt_150To300->Integral());
  sieie_three_or_more_mothers_EB_pt_150To300->Scale(1.0/sieie_three_or_more_mothers_EB_pt_150To300->Integral());
  TH1D *sieie_all_fakes_EE_pt_150To300 = (TH1D*) f->Get("sieie_all_fakes_EE_pt_150To300");
  TH1D *sieie_one_mother_EE_pt_150To300 = (TH1D*) f->Get("sieie_one_mother_EE_pt_150To300");
  TH1D *sieie_two_mothers_EE_pt_150To300 = (TH1D*) f->Get("sieie_two_mothers_EE_pt_150To300");
  TH1D *sieie_three_or_more_mothers_EE_pt_150To300 = (TH1D*) f->Get("sieie_three_or_more_mothers_EE_pt_150To300");
  sieie_all_fakes_EE_pt_150To300->SetLineColor(kBlack);
  sieie_one_mother_EE_pt_150To300->SetLineColor(kRed);
  sieie_two_mothers_EE_pt_150To300->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EE_pt_150To300->SetLineColor(kGreen+3);
  sieie_all_fakes_EE_pt_150To300->SetMarkerColor(kBlack);
  sieie_one_mother_EE_pt_150To300->SetMarkerColor(kRed);
  sieie_two_mothers_EE_pt_150To300->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EE_pt_150To300->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EE_pt_150To300->Scale(1.0/sieie_all_fakes_EE_pt_150To300->Integral());
  sieie_one_mother_EE_pt_150To300->Scale(1.0/sieie_one_mother_EE_pt_150To300->Integral());
  sieie_two_mothers_EE_pt_150To300->Scale(1.0/sieie_two_mothers_EE_pt_150To300->Integral());
  sieie_three_or_more_mothers_EE_pt_150To300->Scale(1.0/sieie_three_or_more_mothers_EE_pt_150To300->Integral());
  TLegend *legend_EB_pt_150To300 = new TLegend(0.60,0.65,0.80,0.85);
  legend_EB_pt_150To300->SetBorderSize(0);
  legend_EB_pt_150To300->SetFillColor(0);
  legend_EB_pt_150To300->AddEntry(sieie_all_fakes_EB_pt_150To300,"all","l");
  legend_EB_pt_150To300->AddEntry(sieie_one_mother_EB_pt_150To300,"1 mother","l");
  legend_EB_pt_150To300->AddEntry(sieie_two_mothers_EB_pt_150To300,"2 mothers","l");
  legend_EB_pt_150To300->AddEntry(sieie_three_or_more_mothers_EB_pt_150To300,"3+ mothers","l");
  TLegend *legend_EE_pt_150To300 = new TLegend(0.60,0.65,0.80,0.85);
  legend_EE_pt_150To300->SetBorderSize(0);
  legend_EE_pt_150To300->SetFillColor(0);
  legend_EE_pt_150To300->AddEntry(sieie_all_fakes_EB_pt_150To300,"all","l");
  legend_EE_pt_150To300->AddEntry(sieie_one_mother_EB_pt_150To300,"1 mother","l");
  legend_EE_pt_150To300->AddEntry(sieie_two_mothers_EB_pt_150To300,"2 mothers","l");
  legend_EE_pt_150To300->AddEntry(sieie_three_or_more_mothers_EB_pt_150To300,"3+ mothers","l");
  TCanvas *c_sieie_distinct_mothers_pt_150To300 = new TCanvas("c_sieie_distinct_mothers_pt_150To300","",1500,600);
  c_sieie_distinct_mothers_pt_150To300->Divide(2,2);
  c_sieie_distinct_mothers_pt_150To300->cd(1);
  sieie_all_fakes_EB_pt_150To300->Draw("HIST");
  sieie_one_mother_EB_pt_150To300->Draw("HISTsame");
  sieie_two_mothers_EB_pt_150To300->Draw("HISTsame");
  sieie_three_or_more_mothers_EB_pt_150To300->Draw("HISTsame");
  sieie_all_fakes_EB_pt_150To300->SetTitle("EB_pt_150To300");
  sieie_all_fakes_EB_pt_150To300->GetXaxis()->SetRangeUser(0,0.025);
  sieie_all_fakes_EB_pt_150To300->SetMaximum(0.3);
  sieie_all_fakes_EB_pt_150To300->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EB_pt_150To300->SetStats(0);
  legend_EB_pt_150To300->Draw();
  c_sieie_distinct_mothers_pt_150To300->cd(2);
  sieie_all_fakes_EE_pt_150To300->Draw("HIST");
  sieie_one_mother_EE_pt_150To300->Draw("HISTsame");
  sieie_two_mothers_EE_pt_150To300->Draw("HISTsame");
  sieie_three_or_more_mothers_EE_pt_150To300->Draw("HISTsame");
  sieie_all_fakes_EE_pt_150To300->SetTitle("EE_pt_150To300");
  sieie_all_fakes_EE_pt_150To300->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_all_fakes_EE_pt_150To300->SetMaximum(0.3);
  sieie_all_fakes_EE_pt_150To300->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EE_pt_150To300->SetStats(0);
  legend_EE_pt_150To300->Draw();
  c_sieie_distinct_mothers_pt_150To300->cd(3);
  sieie_all_fakes_EB_pt_150To300->Draw("HIST");
  sieie_one_mother_EB_pt_150To300->Draw("HISTsame");
  sieie_two_mothers_EB_pt_150To300->Draw("HISTsame");
  sieie_three_or_more_mothers_EB_pt_150To300->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers_pt_150To300->cd(4);
  sieie_all_fakes_EE_pt_150To300->Draw("HIST");
  sieie_one_mother_EE_pt_150To300->Draw("HISTsame");
  sieie_two_mothers_EE_pt_150To300->Draw("HISTsame");
  sieie_three_or_more_mothers_EE_pt_150To300->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers_pt_150To300->SaveAs("dR_cone_study_sieie_distinct_mothers_pt_150To300.png");
  // Stacked sieie plot - pt 300ToInf
  TH1D *sieie_all_fakes_EB_pt_300ToInf = (TH1D*) f->Get("sieie_all_fakes_EB_pt_300ToInf");
  TH1D *sieie_one_mother_EB_pt_300ToInf = (TH1D*) f->Get("sieie_one_mother_EB_pt_300ToInf");
  TH1D *sieie_two_mothers_EB_pt_300ToInf = (TH1D*) f->Get("sieie_two_mothers_EB_pt_300ToInf");
  TH1D *sieie_three_or_more_mothers_EB_pt_300ToInf = (TH1D*) f->Get("sieie_three_or_more_mothers_EB_pt_300ToInf");
  sieie_all_fakes_EB_pt_300ToInf->SetLineColor(kBlack);
  sieie_one_mother_EB_pt_300ToInf->SetLineColor(kRed);
  sieie_two_mothers_EB_pt_300ToInf->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EB_pt_300ToInf->SetLineColor(kGreen+3);
  sieie_all_fakes_EB_pt_300ToInf->SetMarkerColor(kBlack);
  sieie_one_mother_EB_pt_300ToInf->SetMarkerColor(kRed);
  sieie_two_mothers_EB_pt_300ToInf->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EB_pt_300ToInf->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EB_pt_300ToInf->Scale(1.0/sieie_all_fakes_EB_pt_300ToInf->Integral());
  sieie_one_mother_EB_pt_300ToInf->Scale(1.0/sieie_one_mother_EB_pt_300ToInf->Integral());
  sieie_two_mothers_EB_pt_300ToInf->Scale(1.0/sieie_two_mothers_EB_pt_300ToInf->Integral());
  sieie_three_or_more_mothers_EB_pt_300ToInf->Scale(1.0/sieie_three_or_more_mothers_EB_pt_300ToInf->Integral());
  TH1D *sieie_all_fakes_EE_pt_300ToInf = (TH1D*) f->Get("sieie_all_fakes_EE_pt_300ToInf");
  TH1D *sieie_one_mother_EE_pt_300ToInf = (TH1D*) f->Get("sieie_one_mother_EE_pt_300ToInf");
  TH1D *sieie_two_mothers_EE_pt_300ToInf = (TH1D*) f->Get("sieie_two_mothers_EE_pt_300ToInf");
  TH1D *sieie_three_or_more_mothers_EE_pt_300ToInf = (TH1D*) f->Get("sieie_three_or_more_mothers_EE_pt_300ToInf");
  sieie_all_fakes_EE_pt_300ToInf->SetLineColor(kBlack);
  sieie_one_mother_EE_pt_300ToInf->SetLineColor(kRed);
  sieie_two_mothers_EE_pt_300ToInf->SetLineColor(kBlue);
  sieie_three_or_more_mothers_EE_pt_300ToInf->SetLineColor(kGreen+3);
  sieie_all_fakes_EE_pt_300ToInf->SetMarkerColor(kBlack);
  sieie_one_mother_EE_pt_300ToInf->SetMarkerColor(kRed);
  sieie_two_mothers_EE_pt_300ToInf->SetMarkerColor(kBlue);
  sieie_three_or_more_mothers_EE_pt_300ToInf->SetMarkerColor(kGreen+3);
  sieie_all_fakes_EE_pt_300ToInf->Scale(1.0/sieie_all_fakes_EE_pt_300ToInf->Integral());
  sieie_one_mother_EE_pt_300ToInf->Scale(1.0/sieie_one_mother_EE_pt_300ToInf->Integral());
  sieie_two_mothers_EE_pt_300ToInf->Scale(1.0/sieie_two_mothers_EE_pt_300ToInf->Integral());
  sieie_three_or_more_mothers_EE_pt_300ToInf->Scale(1.0/sieie_three_or_more_mothers_EE_pt_300ToInf->Integral());
  TLegend *legend_EB_pt_300ToInf = new TLegend(0.60,0.65,0.80,0.85);
  legend_EB_pt_300ToInf->SetBorderSize(0);
  legend_EB_pt_300ToInf->SetFillColor(0);
  legend_EB_pt_300ToInf->AddEntry(sieie_all_fakes_EB_pt_300ToInf,"all","l");
  legend_EB_pt_300ToInf->AddEntry(sieie_one_mother_EB_pt_300ToInf,"1 mother","l");
  legend_EB_pt_300ToInf->AddEntry(sieie_two_mothers_EB_pt_300ToInf,"2 mothers","l");
  legend_EB_pt_300ToInf->AddEntry(sieie_three_or_more_mothers_EB_pt_300ToInf,"3+ mothers","l");
  TLegend *legend_EE_pt_300ToInf = new TLegend(0.60,0.65,0.80,0.85);
  legend_EE_pt_300ToInf->SetBorderSize(0);
  legend_EE_pt_300ToInf->SetFillColor(0);
  legend_EE_pt_300ToInf->AddEntry(sieie_all_fakes_EB_pt_300ToInf,"all","l");
  legend_EE_pt_300ToInf->AddEntry(sieie_one_mother_EB_pt_300ToInf,"1 mother","l");
  legend_EE_pt_300ToInf->AddEntry(sieie_two_mothers_EB_pt_300ToInf,"2 mothers","l");
  legend_EE_pt_300ToInf->AddEntry(sieie_three_or_more_mothers_EB_pt_300ToInf,"3+ mothers","l");
  TCanvas *c_sieie_distinct_mothers_pt_300ToInf = new TCanvas("c_sieie_distinct_mothers_pt_300ToInf","",1500,600);
  c_sieie_distinct_mothers_pt_300ToInf->Divide(2,2);
  c_sieie_distinct_mothers_pt_300ToInf->cd(1);
  sieie_all_fakes_EB_pt_300ToInf->Draw("HIST");
  sieie_one_mother_EB_pt_300ToInf->Draw("HISTsame");
  sieie_two_mothers_EB_pt_300ToInf->Draw("HISTsame");
  sieie_three_or_more_mothers_EB_pt_300ToInf->Draw("HISTsame");
  sieie_all_fakes_EB_pt_300ToInf->SetTitle("EB_pt_300ToInf");
  sieie_all_fakes_EB_pt_300ToInf->GetXaxis()->SetRangeUser(0,0.025);
  sieie_all_fakes_EB_pt_300ToInf->SetMaximum(0.6);
  sieie_all_fakes_EB_pt_300ToInf->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EB_pt_300ToInf->SetStats(0);
  legend_EB_pt_300ToInf->Draw();
  c_sieie_distinct_mothers_pt_300ToInf->cd(2);
  sieie_all_fakes_EE_pt_300ToInf->Draw("HIST");
  sieie_one_mother_EE_pt_300ToInf->Draw("HISTsame");
  sieie_two_mothers_EE_pt_300ToInf->Draw("HISTsame");
  sieie_three_or_more_mothers_EE_pt_300ToInf->Draw("HISTsame");
  sieie_all_fakes_EE_pt_300ToInf->SetTitle("EE_pt_300ToInf");
  sieie_all_fakes_EE_pt_300ToInf->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_all_fakes_EE_pt_300ToInf->SetMaximum(0.6);
  sieie_all_fakes_EE_pt_300ToInf->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_all_fakes_EE_pt_300ToInf->SetStats(0);
  legend_EE_pt_300ToInf->Draw();
  c_sieie_distinct_mothers_pt_300ToInf->cd(3);
  sieie_all_fakes_EB_pt_300ToInf->Draw("HIST");
  sieie_one_mother_EB_pt_300ToInf->Draw("HISTsame");
  sieie_two_mothers_EB_pt_300ToInf->Draw("HISTsame");
  sieie_three_or_more_mothers_EB_pt_300ToInf->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers_pt_300ToInf->cd(4);
  sieie_all_fakes_EE_pt_300ToInf->Draw("HIST");
  sieie_one_mother_EE_pt_300ToInf->Draw("HISTsame");
  sieie_two_mothers_EE_pt_300ToInf->Draw("HISTsame");
  sieie_three_or_more_mothers_EE_pt_300ToInf->Draw("HISTsame");
  gPad->SetLogy();
  c_sieie_distinct_mothers_pt_300ToInf->SaveAs("dR_cone_study_sieie_distinct_mothers_pt_300ToInf.png");

  // single pion vs. eta
  TH1D *sieie_pion_EB = (TH1D*) f->Get("sieie_single_pion_mother_EB");
  TH1D *sieie_eta_EB = (TH1D*) f->Get("sieie_single_eta_mother_EB");
  sieie_pion_EB->Scale(1.0/sieie_pion_EB->Integral());
  sieie_eta_EB->Scale(1.0/sieie_eta_EB->Integral());
  TLegend *legend_pion_EB = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EB->SetBorderSize(0);
  legend_pion_EB->SetFillColor(0);
  legend_pion_EB->AddEntry(sieie_pion_EB,"pi0 mother","l");
  legend_pion_EB->AddEntry(sieie_eta_EB,"eta mother","l");
  TH1D *sieie_pion_EE = (TH1D*) f->Get("sieie_single_pion_mother_EE");
  TH1D *sieie_eta_EE = (TH1D*) f->Get("sieie_single_eta_mother_EE");
  sieie_pion_EE->Scale(1.0/sieie_pion_EE->Integral());
  sieie_eta_EE->Scale(1.0/sieie_eta_EE->Integral());
  TLegend *legend_pion_EE = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EE->SetBorderSize(0);
  legend_pion_EE->SetFillColor(0);
  legend_pion_EE->AddEntry(sieie_pion_EE,"pi0 mother","l");
  legend_pion_EE->AddEntry(sieie_eta_EE,"eta mother","l");
  TCanvas *c_sieie_pion_eta = new TCanvas("c_sieie_pion_eta","",1500,600);
  c_sieie_pion_eta->Divide(2,1);
  c_sieie_pion_eta->cd(1);
  sieie_pion_EB->Draw("HIST");
  sieie_eta_EB->Draw("HISTsame");
  sieie_pion_EB->SetTitle("EB");
  sieie_pion_EB->SetLineColor(kRed);
  sieie_pion_EB->GetXaxis()->SetRangeUser(0,0.025);
  sieie_pion_EB->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EB->SetMaximum(0.2);
  sieie_pion_EB->SetStats(0);
  legend_pion_EB->Draw();
  c_sieie_pion_eta->cd(2);
  sieie_pion_EE->Draw("HIST");
  sieie_eta_EE->Draw("HISTsame");
  sieie_pion_EE->SetTitle("EE");
  sieie_pion_EE->SetLineColor(kRed);
  sieie_pion_EE->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_pion_EE->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EE->SetMaximum(0.2);
  sieie_pion_EE->SetStats(0);
  legend_pion_EE->Draw();
  c_sieie_pion_eta->SaveAs("dR_cone_study_sieie_single_pion_eta_mothers.png");
  // single pion vs. eta - pt 50To150
  TH1D *sieie_pion_EB_pt_50To150 = (TH1D*) f->Get("sieie_single_pion_mother_EB_pt_50To150");
  TH1D *sieie_eta_EB_pt_50To150 = (TH1D*) f->Get("sieie_single_eta_mother_EB_pt_50To150");
  sieie_pion_EB_pt_50To150->Scale(1.0/sieie_pion_EB_pt_50To150->Integral());
  sieie_eta_EB_pt_50To150->Scale(1.0/sieie_eta_EB_pt_50To150->Integral());
  TLegend *legend_pion_EB_pt_50To150 = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EB_pt_50To150->SetBorderSize(0);
  legend_pion_EB_pt_50To150->SetFillColor(0);
  legend_pion_EB_pt_50To150->AddEntry(sieie_pion_EB_pt_50To150,"pi0 mother","l");
  legend_pion_EB_pt_50To150->AddEntry(sieie_eta_EB_pt_50To150,"eta mother","l");
  TH1D *sieie_pion_EE_pt_50To150 = (TH1D*) f->Get("sieie_single_pion_mother_EE_pt_50To150");
  TH1D *sieie_eta_EE_pt_50To150 = (TH1D*) f->Get("sieie_single_eta_mother_EE_pt_50To150");
  sieie_pion_EE_pt_50To150->Scale(1.0/sieie_pion_EE_pt_50To150->Integral());
  sieie_eta_EE_pt_50To150->Scale(1.0/sieie_eta_EE_pt_50To150->Integral());
  TLegend *legend_pion_EE_pt_50To150 = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EE_pt_50To150->SetBorderSize(0);
  legend_pion_EE_pt_50To150->SetFillColor(0);
  legend_pion_EE_pt_50To150->AddEntry(sieie_pion_EE_pt_50To150,"pi0 mother","l");
  legend_pion_EE_pt_50To150->AddEntry(sieie_eta_EE_pt_50To150,"eta mother","l");
  TCanvas *c_sieie_pion_eta_pt_50To150 = new TCanvas("c_sieie_pion_eta_pt_50To150","",1500,600);
  c_sieie_pion_eta_pt_50To150->Divide(2,1);
  c_sieie_pion_eta_pt_50To150->cd(1);
  sieie_pion_EB_pt_50To150->Draw("HIST");
  sieie_eta_EB_pt_50To150->Draw("HISTsame");
  sieie_pion_EB_pt_50To150->SetTitle("EB_pt_50To150");
  sieie_pion_EB_pt_50To150->SetLineColor(kRed);
  sieie_pion_EB_pt_50To150->GetXaxis()->SetRangeUser(0,0.025);
  sieie_pion_EB_pt_50To150->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EB_pt_50To150->SetMaximum(0.2);
  sieie_pion_EB_pt_50To150->SetStats(0);
  legend_pion_EB_pt_50To150->Draw();
  c_sieie_pion_eta_pt_50To150->cd(2);
  sieie_pion_EE_pt_50To150->Draw("HIST");
  sieie_eta_EE_pt_50To150->Draw("HISTsame");
  sieie_pion_EE_pt_50To150->SetTitle("EE_pt_50To150");
  sieie_pion_EE_pt_50To150->SetLineColor(kRed);
  sieie_pion_EE_pt_50To150->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_pion_EE_pt_50To150->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EE_pt_50To150->SetMaximum(0.2);
  sieie_pion_EE_pt_50To150->SetStats(0);
  legend_pion_EE_pt_50To150->Draw();
  c_sieie_pion_eta_pt_50To150->SaveAs("dR_cone_study_sieie_single_pion_eta_mothers_pt_50To150.png");
  // single pion vs. eta - pt 150To300
  TH1D *sieie_pion_EB_pt_150To300 = (TH1D*) f->Get("sieie_single_pion_mother_EB_pt_150To300");
  TH1D *sieie_eta_EB_pt_150To300 = (TH1D*) f->Get("sieie_single_eta_mother_EB_pt_150To300");
  sieie_pion_EB_pt_150To300->Scale(1.0/sieie_pion_EB_pt_150To300->Integral());
  sieie_eta_EB_pt_150To300->Scale(1.0/sieie_eta_EB_pt_150To300->Integral());
  TLegend *legend_pion_EB_pt_150To300 = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EB_pt_150To300->SetBorderSize(0);
  legend_pion_EB_pt_150To300->SetFillColor(0);
  legend_pion_EB_pt_150To300->AddEntry(sieie_pion_EB_pt_150To300,"pi0 mother","l");
  legend_pion_EB_pt_150To300->AddEntry(sieie_eta_EB_pt_150To300,"eta mother","l");
  TH1D *sieie_pion_EE_pt_150To300 = (TH1D*) f->Get("sieie_single_pion_mother_EE_pt_150To300");
  TH1D *sieie_eta_EE_pt_150To300 = (TH1D*) f->Get("sieie_single_eta_mother_EE_pt_150To300");
  sieie_pion_EE_pt_150To300->Scale(1.0/sieie_pion_EE_pt_150To300->Integral());
  sieie_eta_EE_pt_150To300->Scale(1.0/sieie_eta_EE_pt_150To300->Integral());
  TLegend *legend_pion_EE_pt_150To300 = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EE_pt_150To300->SetBorderSize(0);
  legend_pion_EE_pt_150To300->SetFillColor(0);
  legend_pion_EE_pt_150To300->AddEntry(sieie_pion_EE_pt_150To300,"pi0 mother","l");
  legend_pion_EE_pt_150To300->AddEntry(sieie_eta_EE_pt_150To300,"eta mother","l");
  TCanvas *c_sieie_pion_eta_pt_150To300 = new TCanvas("c_sieie_pion_eta_pt_150To300","",1500,600);
  c_sieie_pion_eta_pt_150To300->Divide(2,1);
  c_sieie_pion_eta_pt_150To300->cd(1);
  sieie_pion_EB_pt_150To300->Draw("HIST");
  sieie_eta_EB_pt_150To300->Draw("HISTsame");
  sieie_pion_EB_pt_150To300->SetTitle("EB_pt_150To300");
  sieie_pion_EB_pt_150To300->SetLineColor(kRed);
  sieie_pion_EB_pt_150To300->GetXaxis()->SetRangeUser(0,0.025);
  sieie_pion_EB_pt_150To300->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EB_pt_150To300->SetMaximum(0.4);
  sieie_pion_EB_pt_150To300->SetStats(0);
  legend_pion_EB_pt_150To300->Draw();
  c_sieie_pion_eta_pt_150To300->cd(2);
  sieie_pion_EE_pt_150To300->Draw("HIST");
  sieie_eta_EE_pt_150To300->Draw("HISTsame");
  sieie_pion_EE_pt_150To300->SetTitle("EE_pt_150To300");
  sieie_pion_EE_pt_150To300->SetLineColor(kRed);
  sieie_pion_EE_pt_150To300->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_pion_EE_pt_150To300->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EE_pt_150To300->SetMaximum(0.4);
  sieie_pion_EE_pt_150To300->SetStats(0);
  legend_pion_EE_pt_150To300->Draw();
  c_sieie_pion_eta_pt_150To300->SaveAs("dR_cone_study_sieie_single_pion_eta_mothers_pt_150To300.png");
  // single pion vs. eta - pt 300ToInf
  TH1D *sieie_pion_EB_pt_300ToInf = (TH1D*) f->Get("sieie_single_pion_mother_EB_pt_300ToInf");
  TH1D *sieie_eta_EB_pt_300ToInf = (TH1D*) f->Get("sieie_single_eta_mother_EB_pt_300ToInf");
  sieie_pion_EB_pt_300ToInf->Scale(1.0/sieie_pion_EB_pt_300ToInf->Integral());
  sieie_eta_EB_pt_300ToInf->Scale(1.0/sieie_eta_EB_pt_300ToInf->Integral());
  TLegend *legend_pion_EB_pt_300ToInf = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EB_pt_300ToInf->SetBorderSize(0);
  legend_pion_EB_pt_300ToInf->SetFillColor(0);
  legend_pion_EB_pt_300ToInf->AddEntry(sieie_pion_EB_pt_300ToInf,"pi0 mother","l");
  legend_pion_EB_pt_300ToInf->AddEntry(sieie_eta_EB_pt_300ToInf,"eta mother","l");
  TH1D *sieie_pion_EE_pt_300ToInf = (TH1D*) f->Get("sieie_single_pion_mother_EE_pt_300ToInf");
  TH1D *sieie_eta_EE_pt_300ToInf = (TH1D*) f->Get("sieie_single_eta_mother_EE_pt_300ToInf");
  sieie_pion_EE_pt_300ToInf->Scale(1.0/sieie_pion_EE_pt_300ToInf->Integral());
  sieie_eta_EE_pt_300ToInf->Scale(1.0/sieie_eta_EE_pt_300ToInf->Integral());
  TLegend *legend_pion_EE_pt_300ToInf = new TLegend(0.60,0.65,0.80,0.85);
  legend_pion_EE_pt_300ToInf->SetBorderSize(0);
  legend_pion_EE_pt_300ToInf->SetFillColor(0);
  legend_pion_EE_pt_300ToInf->AddEntry(sieie_pion_EE_pt_300ToInf,"pi0 mother","l");
  legend_pion_EE_pt_300ToInf->AddEntry(sieie_eta_EE_pt_300ToInf,"eta mother","l");
  TCanvas *c_sieie_pion_eta_pt_300ToInf = new TCanvas("c_sieie_pion_eta_pt_300ToInf","",1500,600);
  c_sieie_pion_eta_pt_300ToInf->Divide(2,1);
  c_sieie_pion_eta_pt_300ToInf->cd(1);
  sieie_pion_EB_pt_300ToInf->Draw("HIST");
  sieie_eta_EB_pt_300ToInf->Draw("HISTsame");
  sieie_pion_EB_pt_300ToInf->SetTitle("EB_pt_300ToInf");
  sieie_pion_EB_pt_300ToInf->SetLineColor(kRed);
  sieie_pion_EB_pt_300ToInf->GetXaxis()->SetRangeUser(0,0.025);
  sieie_pion_EB_pt_300ToInf->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EB_pt_300ToInf->SetMaximum(0.7);
  sieie_pion_EB_pt_300ToInf->SetStats(0);
  legend_pion_EB_pt_300ToInf->Draw();
  c_sieie_pion_eta_pt_300ToInf->cd(2);
  sieie_pion_EE_pt_300ToInf->Draw("HIST");
  sieie_eta_EE_pt_300ToInf->Draw("HISTsame");
  sieie_pion_EE_pt_300ToInf->SetTitle("EE_pt_300ToInf");
  sieie_pion_EE_pt_300ToInf->SetLineColor(kRed);
  sieie_pion_EE_pt_300ToInf->GetXaxis()->SetRangeUser(0.01,0.06);
  sieie_pion_EE_pt_300ToInf->GetXaxis()->SetTitle("#sigma_{i#etai#eta}");
  sieie_pion_EE_pt_300ToInf->SetMaximum(0.7);
  sieie_pion_EE_pt_300ToInf->SetStats(0);
  legend_pion_EE_pt_300ToInf->Draw();
  c_sieie_pion_eta_pt_300ToInf->SaveAs("dR_cone_study_sieie_single_pion_eta_mothers_pt_300ToInf.png");

  // pt of fakes
  TCanvas *c_pt = new TCanvas("c_pt","",1500,600);
  c_pt->Divide(2,1);
  TH1D *pt_all_fakes_EB = (TH1D*) f->Get("pt_all_fakes_EB");
  c_pt->cd(1);
  pt_all_fakes_EB->Draw("HIST");
  pt_all_fakes_EB->SetTitle("EB");
  pt_all_fakes_EB->GetXaxis()->SetTitle("p_{T} (GeV)");
  pt_all_fakes_EB->GetXaxis()->SetRangeUser(0,1500);
  gPad->SetLogy();
  TH1D *pt_all_fakes_EE = (TH1D*) f->Get("pt_all_fakes_EE");
  c_pt->cd(2);
  pt_all_fakes_EE->Draw("HIST");
  pt_all_fakes_EE->SetTitle("EE");
  pt_all_fakes_EE->GetXaxis()->SetTitle("p_{T} (GeV)");
  pt_all_fakes_EE->GetXaxis()->SetRangeUser(0,1000);
  gPad->SetLogy();
  c_pt->SaveAs("dR_cone_study_pt_all_fakes.png");

  // eta vs. phi
  TCanvas *c_eta_phi = new TCanvas("c_eta_phi","",800,600);
  TH2D *eta_vs_phi = (TH2D*) f->Get("eta_vs_phi_all_fakes");
  eta_vs_phi->Draw("colz");
  c_eta_phi->SaveAs("dR_cone_study_eta_phi_all_fakes.png");
  
}
